services:
  - type: web
    name: tekrowe-blog-automation-backend
    env: python
    plan: free
    rootDir: backend       # ðŸ‘ˆ tells Render to use backend/ as working directory
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: DATABASE_URL
      # value: sqlite:///blog_automation.db
        value: postgresql://blogpost_xdx4_user:Yc03a5o6J9AcaBXSwbM3OJPXsofdfEqh@dpg-d4bhe2f5r7bs739663e0-a.singapore-postgres.render.com/blogpost_xdx4
      - key: OPENAI_API_KEY
        sync: false
      - key: ENVIRONMENT
        value: production
    healthCheckPath: /docs
    autoDeploy: false  # Set to false to prevent automatic restarts on code push
